apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
  namespace: {{ .Release.Namespace }}
data:
  infraClusterNamespace: {{ .Values.infra.namespace | quote }}
  infraClusterLabels: {{ .Values.infra.labels | quote }}